import React from 'react';
import AnimatedCard from '@/app/components/AnimatedBox';

const questions = [
  'Who is the messiest?',
  'Who is the boss?',
  'Who is the grumpiest?',
  'Who has the worst memory?',
  'Who is the party animal?',
  'Who has had the most partners?',
  'Who smells the best?',
  'Who is the best looking?',
  'Who is the most romantic?',
  'Who has the best sense of humour?',
  'Who is the most organised?',
  'Who spends the most time on social media?',
  'Who takes the longest to get ready?',
  'Who is the fussiest eater?',
  'Who has the best job?',
  'Who is the best cook?',
  'Who is the smartest?',
  'Who\'s more bothered about their looks?',
  'Who is the better driver?',
  'Who is the best dancer?',
  'Who is the laziest?',
  'Who can eat the most?',
  'Who would be most likely to trip over?',
  'Who wastes the most money?',
  'Who has the weirdest orgasm face?',
  'Who has the worst habits?',
  'Who is the most talkative?',
  'Who is the most argumentative?',
  'Who made the first move?',
  'Who could talk their way out of a speeding ticket?',
  'Who is in control of music in the car?',
  'Who is more likely to eat out or order in?',
  'Who hogs the covers more in bed?',
  'Who is the earlier riser?',
  'Who stays up the latest?',
  'Who is the better singer?',
  'Who is more likely to start a fight?',
  'Who is more likely to save their money?',
  'Who is the more dramatic one?',
  'Who is more likely to keep a secret?',
  'Who would last longer on a deserted island?',
  'Who is better at giving presents?',
  'Who has more clothes?',
  'Who has more shoes?',
  'Who is more likely to be late?',
  'Who swears more?',
  'Who will likely have a hangover after the big day?',
  'Who is the least affectionate?',
  'Who gives the best hugs?',
  'Who is the most immature?',
  'Who has the nicest hair?',
  'Who gets their way the most?',
  'Who is the best with children?',
  'Who makes the best cups of tea?',
  'Who has the worst temper?',
  'Who gets scared the most?',
  'Who would be more likely to have plastic surgery?',
  'Who would cry at a movie?',
  'Who gets the last word?',
  'Who is the one to remove the spider from the room?',
  'Who has had the most jobs?',
  'Who said ‘I love you’ first?',
  'Who is the funniest?',
  'Who is the most competitive?',
  'Who kills the spiders?',
  'Who is more adventurous?',
  'Who is the clumsiest?',
  'Who is the most honest?',
  'Who is the biggest sulker?',
  'Who would have the hardiest legs after a month?',
  'Who is the most forgetful?',
  'Who has the best taste in music?',
  'Who is the best at public speaking?',
  'Who is better at gardening?',
  'Who is the biggest fan of outdoor activities?',
  'Who is the most skilled at writing poetry or stories?',
  'Who is the best at giving advice?',
  'Who is the most knowledgeable about fashion trends?',
  'Who is the most skilled at solving puzzles?',
  'Who is the biggest fan of documentaries?',
];

const YourComponent = () => {
    return (
      <div className="flex justify-center items-center h-screen">
        <AnimatedCard questions={questions} />
      </div>
    );
  };
  
export default YourComponent;
